routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('home');
})->name('home');

/*Route::get('/workerAdd', 'WorkerController@view')->name('worker_add');
Route::get('/professions', 'ProfessionController@getList')->name('professions');
Route::get('/profession_add', function () {
    return view('professionAdd');
})->name('profession_add');*/

/*Route::get('/profession_edit/{id}', 'ProfessionController@view')->name('profession_edit');
Route::get('/profession_delete/{id}', 'ProfessionController@delete')->name('profession_delete');
Route::post('/profession_update_submit/{id}', 'ProfessionController@update')->name('profession_update_submit');
Route::post('/profession_submit', 'ProfessionController@update')->name('profession_submit');*/

/*Route::get('/workers', 'WorkerController@getList')->name('workers');
Route::get('/worker_update/{id}', 'WorkerController@view')->name('worker_update');
Route::get('/worker_delete/{id}', 'WorkerController@delete')->name('worker_delete');
Route::post('/worker_update_submit/{id}','WorkerController@update')->name('worker_update_submit');
Route::post('/worker_submit', 'WorkerController@update')->name('worker_submit');*/

/*Route::get('/city_add', 'RegionController@getList')->name('city_add');*/

/*Route::get('/cities', 'CityController@getList')->name('cities');
Route::get('/city_update/{id}', 'CityController@view')->name('city_update');
Route::get('/city_delete/{id}', 'CityController@delete')->name('city_delete');
Route::post('/city_update_submit/{id}', 'CityController@update')->name('city_update_submit');
Route::post('/city_submit', 'CityController@submit')->name('city_submit');*/

Route::resource('workers', 'WorkerController');
Route::resource('professions', 'ProfessionController');
Route::resource('cities', 'CityController',
    ['except' => ['show']]);
Route::resource('routes', 'RouteController',
    ['except' => ['create', 'show', 'edit' ]]);
Route::resource('routes', 'RouteController',
    ['except' => ['create', 'show', 'edit' ]]);
Route::resource('timetables', 'TimetableController',
    ['except' => ['show']]);
Route::post('check_busy_time', 'TimetableController@checkBusyTime')->name('check_busy_time');
Route::resource('buses', 'BusController',
    ['except' => ['create', 'show', 'edit' ]]);
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

resources/views/buses.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-body">
                    <div class="navbar navbar-toggleable-md navbar-light bg-faded">
                        <button type="button" class="btn btn-primary btn-sm" id="newBus" data-toggle="modal" data-target="#newBusModal">
                            Додати Запис
                        </button>
                    </div>
                    @include('modal.busesModal')

                    <table class="table table hover btn-sm" id="table">
                            <thead class="thead-light">
                            <tr>
                            <th>Модель авто</th>
                            <th>Номерний знак</th>
                            <th>Кількість сидяч місць</th>
                            <th>Розхід топлива </th>
                            <th>Тип маршруту</th>
                            <th>Тип палива</th>
                            <th>Рік випуску авто</th>
                            <th>Дата страхування</th>
                            <th>Дата закінчення страхування</th>
                            <th>Пробіг авто</th>
                            <th></th>
                            <th></th>
                        </tr>
                        </thead>

                        <tbody>
                        @foreach($buses as $bus)
                            <tr>
                                <td><b>{{ $bus->model }}</b></td>
                                <td>{{ $bus->carNumber }}</td>
                                <td>{{ $bus->seats }}</td>
                                <td>{{ $bus->fuelConsumption }}</td>
                                <td>{{ $bus->typeOfTransportation}}</td>
                                <td>{{ $bus->typeOfFuel}}</td>
                                <td>{{ $bus->dateOfManufacture}}</td>
                                <td>{{ $bus->insuranceFrom}}</td>
                                <td>{{ $bus->insuranceTo}}</td>
                                <td>{{ $bus->run}}</td>
                                <td>
                                    <a href="#" id="editBus"
                                       class="editBus-modal btn btn-sm"
                                       data-id="{{$bus->id}}"
                                       data-model="{{ $bus->model }}"
                                       data-car_number="{{ $bus->carNumber }}"
                                       data-seats="{{ $bus->seats }}"
                                       data-fuel_consumption="{{ $bus->fuelConsumption }}"
                                       data-type_of_transportation="{{ $bus->typeOfTransportation }}"
                                       data-type_of_fuel="{{ $bus->typeOfFuel }}"
                                       data-date_of_manufacture="{{ $bus->dateOfManufacture }}"
                                       data-insurance_from="{{ $bus->insuranceFrom }}"
                                       data-insurance_to="{{ $bus->insuranceTo }}"
                                       data-run="{{ $bus->run }}">
                                        <i  class=" fa fa-pen"></i>
                                    </a>
                                </td>
                                <td>
                                    <a href="#" id="deleteBus" class="deleteBus-modal btn btn-sm"
                                       data-id="{{$bus->id}}">
                                        <i style="color: #d12507" class="fa fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                        <tfoot></tfoot>
                    </table>

                    @if($buses->total() > $buses->count())
                        <div class="row justify-content-center">
                            {{ $buses->links() }}
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/cities.blade.php
@extends('layouts.app')
@section('content')
    <div class="d-flex justify-content-left">
        <a href="{{ route('cities.create') }}">
            <button type="button" class=" ml-4 btn btn-primary">Добавить населенный пункт</button>
        </a>
    </div>
    <br>
    {{--<div class="container">
        <form class="form-inline" method="GET" action="{{ route('cities.index')}}">
            {{ csrf_field() }}
            <div class="form-group mx-sm-3 mb-2">
                <label for="region">Выберите регион </label>
                <select name="region" id="region" class="form-control">
                    @foreach($regions as $region)
                        <option value="{{ $region['id'] }}">{{$region['name']}}</option>
                    @endforeach
                </select>
            </div>
            <button type="submit" class="btn btn-primary mb-2">Выбрать</button>
            <a href="{{ route('cities.index') }}">
                <button type="button" class="ml-3 btn btn-danger mb-2">Сбросить</button>
            </a>
        </form>
    </div>--}}

    <div class="container">
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">Місто</th>
                <th scope="col">Область</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            @foreach($cities as $city)
                <tr>
                    <td>{{ $city->name }}</td>
                    <td>{{ $city->getRegionName->name }}</td>
                    <td>
                        <a href="{{ route('cities.edit', ['id' => $city->id] ) }}"> Подробнее </a>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>

    </div>

    <div class="d-flex justify-content-center">
        {{ $cities->links() }}
    </div>



@endsection

resources/views/cityAdd.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        @if (isset($city))
            <form method="POST" action="{{ route('cities.update', $city->id)}}">
                {{ method_field('PATCH') }}
                @else
                    <form method="POST" action="{{ route('cities.store') }}">
                        @endif
                        {{ csrf_field() }}
                        <div class="row">
                            <div class="col">
                                <label for="name">Название</label>
                                <input type="text" name="name" class="form-control" id="name"
                                       value="{{ $city->name ?? '' }}">
                            </div>
                            <div class="col">
                                <label for="regionId">Область</label>
                                <select name="regionId" id="regionId" class="form-control">
                                    @if (isset($city))
                                        <option value="{{$city->regionId}}"
                                                selected>{{$city->getRegionName->name}}</option>
                                    @endif
                                    @foreach($regions as $region)
                                        <option value="{{ $region->id }}">{{$region->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <br>
                    @if (!isset($city))
                            <button type="submit" class="ml-3 btn btn-success">Добавить населенный пункт</button>
                    </form>
                    @else
                    <button type="submit" class="ml-3 btn btn-success">Сохранить населенный пункт</button>
            </form>

            <form method="POST" action="{{ route('cities.destroy', $city->id) }} ">
                {{ method_field('DELETE') }}
                {{ csrf_field() }}
                <button type="submit" class="ml-3 btn btn-danger">Удалить населенный пункт</button>
            </form>
                    @endif

        <a href="{{ route('cities.index')}}">
            <button type="button" class="btn btn-primary">Назад</button>
        </a>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    @if (session('status'))
                        <div class="alert alert-success">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/professionAdd.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="d-flex justify-content-center">
            @if (isset($profession))
                <form class="form-inline" method="POST" action="{{ route('professions.update', $profession->id)}}">
                    {{ method_field('PATCH') }}
                    @else
                        <form class="form-inline" method="POST" action="{{ route('professions.store') }}">
                            @endif
                            {{ csrf_field() }}
                            <div class="form-group mx-sm-3 mb-2">
                                <label for="name" class="sr-only">Новая должность</label>
                                <input name="name" type="text" class="form-control" id="name"
                                       placeholder="Новая должность"
                                       @if(isset($profession))
                                       value="{{$profession->name ?? ''}}"
                                        @endif>
                            </div>
                            <button type="submit" class="btn btn-primary mb-2">
                                @if(isset($profession))Сохранить
                                @else Добавить
                                @endif
                            </button>
                        </form>
        </div>
    </div>
@endsection

resources/views/professions.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        <div class="d-flex justify-content-center">
            <a href="{{route('professions.create')}}">
                <button type="button" class="btn btn-primary mb-2">Додати</button>
            </a>
        </div>
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">Посади</th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            @foreach($professions as $profession)
                <tr>
                    <td>{{ $profession->name }}</td>
                    <td>
                        <a href="{{ route('professions.edit', $profession->id) }}">
                            Редагувати
                        </a>
                    </td>
                    <td>
                            <form action="{{ route('professions.destroy', $profession->id) }}" method="POST">
                            {{ method_field('DELETE') }}
                            {{ csrf_field() }}
                           <button type="submit">Видалити</button>
                        </form>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
@endsection

resources/views/routes.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <div class="navbar navbar-toggleable-md navbar-light bg-faded">
                        <button type="button" class="btn btn-primary btn-sm" id="newRoute" data-toggle="modal" data-target="#newRouteModal">
                            Додати Запис
                        </button>
                    </div>
                    @include('modal.routeModal')
                        <table class="table table hover btn-sm" id="table">
                        <thead class="thead-light">
                        <tr>
                            <th>Назва маршруту</th>
                            <th>Відстань</th>
                            <th>Ціна </th>
                            <th></th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($routes as $route)
                            <tr>
                                <td>{{ $route->name }}</td>
                                <td>{{ $route->distance }}</td>
                                <td>{{ $route->price }}</td>
                                <td>
                                    <a href="#" id="editRoute" class="editRoute-modal btn btn-sm" data-id="{{$route->id}}"
                                       data-name="{{$route->name}}" data-distance="{{$route->distance}}"
                                       data-price="{{$route->price}}">
                                        <i  class=" fa fa-pen"></i>
                                    </a>
                                    <a href="#" id="deleteRoute" class="deleteRoute-modal btn btn-sm" data-id="{{$route->id}}">
                                        <i style="color: #d12507" class="fa fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                        <tfoot></tfoot>
                    </table>
                    @if($routes->total() > $routes->count())
                        <div class="row justify-content-center">
                            {{ $routes->links() }}
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/timetables.blade.php
@extends('layouts.app')
@section('content')
    <div class="row justify-content-center">
        <div class="col-md-10">
            <div class="card">
                <div class="card-body">
                    <div class="navbar navbar-toggleable-md navbar-light bg-faded">
                        <button type="button" class="btn btn-primary btn-sm" id="newTimetable" data-toggle="modal" data-target="#newTimetableModal">
                            Додати Запис
                        </button>
                        <a class="btn-sm btn-success" href="#">Історія маршруів</a>
                    </div>
                    
                    @include('modal.timetablesModal')

                    <table class="table table hover btn-sm" id="table">
                        <thead class="thead-light">
                        <tr>
                            <th>Маршрут</th>
                            <th>Автобус</th>
                            <th>Водій</th>
                            <th>Час віправвлення </th>
                            <th>Час прибуття</th>
                            <th></th>
                        </tr>
                        </thead>

                        <tbody>
                        @foreach($timetables as $timetable)
                            <tr>
                                <td>{{ $startingCity . ' - ' . $timetable->route->name }}</td>
                                <td>{{ $timetable->bus->model . ' ' . $timetable->bus->carNumber }}</td>
                                <td>{{ $timetable->worker->firstName . ' ' . $timetable->worker->lastName }}</td>
                                <td>{{ $timetable->departureTime}}</td>
                                <td>{{ $timetable->arrivalTime}}</td>
                                <td>
                                    <a href="#" id="editTimetable" class="edit-modal btn btn-sm"
                                       data-id="{{$timetable->id}}"
                                       data-bus_id="{{$timetable->bus_id}}"
                                       data-route_id="{{$timetable->route_id}}"
                                       data-driver_id="{{ $timetable->worker_id }}"
                                       data-departure_time="{{ $timetable->departureTime }}"
                                       data-arrival_time="{{ $timetable->arrivalTime }}"> <i class="fa fa-pen"></i>
                                    </a>
                                    <a href="#" id="delete" class="delete-modal btn btn-sm" data-id="{{$timetable->id}}">
                                        <i style="color: #d12507" class="fa fa-trash"></i>
                                    </a>
                                </td>
                            </tr>
                        @endforeach
                        </tbody>
                        <tfoot></tfoot>
                    </table>
                     @if($timetables->total() > $timetables->count())
                         <div class="row justify-content-center">
                                         {{ $timetables->links() }}
                         </div>
                     @endif
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/workerAdd.blade.php
@extends('layouts.app')
@section('content')
    <div class="container">
        @if (isset($worker))
            <form method="POST" action="{{ route('workers.update', $worker->id)}}">
                {{ method_field('PATCH') }}
                @else
                    <form method="POST" action="{{ route('workers.store') }}">
                        @endif

                        {{ csrf_field() }}
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="firstName">Имя</label>
                                <input type="text" name="firstName" class="form-control" id="firstName"
                                       value="{{ $worker->firstName ?? ''}}">
                            </div>

                            <div class="form-group col-md-6">
                                <label for="lastName">Фамилия</label>
                                <input type="text" name="lastName" class="form-control" id="lastName"
                                       value="{{ $worker->lastName ?? ''}}">
                            </div>
                        </div>

                        <div class="form-row">


                            <div class="form-group col-md-6">
                                <label for="professionId">Должность</label>
                                <select name="professionId" id="professionId" class="form-control">
                                    @foreach($professions as $profession)
                                        <option value="{{ $profession->id }}"
                                        @if(isset($worker) && $profession->id == $worker->professionId ?? '')
                                            selected="selected"
                                                @endif
                                        >{{$profession->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group col-md-6">
                                <br>
                            <a href="{{ route('professions.index') }}">
                                <button type="button" class="mt-1 btn btn-primary">Редактировать должности</button>
                            </a>
                        </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-12">
                                <label for="homeAddress">Адресс</label>
                                <input type="text" name="homeAddress" class="form-control" id="homeAddress"
                                       value="{{ $worker->homeAddress ?? '' }}">
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="phoneNumber">Номер телефона</label>
                                <input type="text" name="phoneNumber" class="form-control" id="phoneNumber"
                                       @if (isset($worker))
                                       value="{{ $worker->phoneNumber ?? '' }}">
                                @else
                                    value="380">
                                @endif
                            </div>
                            <div class="form-group col-md-6">
                                <label for="birthday">День рождения</label>
                                <input type="date" name="birthday" class="form-control" id="birthday"
                                       value="{{ $worker->birthday ?? '' }}">
                            </div>
                        </div>
                        <div class="d-flex justify-content-left">


                            @if (isset($worker))
                                <button type="submit" class="ml-3 btn btn-success">Сохранить работника</button>

                    </form>

                    <form action="{{ route('workers.destroy', $worker->id) }}" method="POST">
                        {{ method_field('DELETE') }}
                        {{ csrf_field() }}
                            <button type="submit" class="ml-3 btn btn-danger">Удалить работника</button>
                    </form>
                            @else
                                <button type="submit" class="ml-3 btn btn-primary">Добавить работника</button>
                            @endif
                        </div>
                    </form>
    <a href="{{ route('workers.index')}}">
        <button type="button" class="btn btn-primary">Назад</button>
    </a>
    </div>
@endsection

resources/views/workers.blade.php
@extends('layouts.app')
@section('content')
    <div class="d-flex justify-content-left">
        <a href="{{ route('workers.create') }}">
            <button type="button" class="ml-4 btn btn-primary">Добавить работника</button>
        </a>
    </div>
    <br>
    <div class="container">
        <form class="form-inline" method="GET" action="{{ route('workers.index')}}">
            {{ csrf_field() }}
            <div class="form-group mx-sm-3 mb-2">
                <label for="profession">Выберите должность </label>
                <select name="profession" id="profession" class="form-control">
                    @foreach($professions as $profession)
                        <option value="{{ $profession['id'] }}">{{$profession['name']}}</option>
                    @endforeach
                </select>
            </div>
            <button type="submit" class="btn btn-primary mb-2">Выбрать</button>
            <a href="{{ route('workers.index') }}">
                <button type="button" class="ml-3 btn btn-danger mb-2">Сбросить</button>
            </a>
        </form>
    </div>

    <div class="container">
        <table class="table">
            <thead class="thead-dark">
            <tr>
                <th scope="col">Имя</th>
                <th scope="col">Фамилия</th>
                <th scope="col">Должность</th>
                <th scope="col"></th>
            </tr>
            </thead>
            <tbody>
            @foreach($workers as $worker)
            <tr>
                <td>{{ $worker->firstName }}</td>
                <td>{{ $worker->lastName }}</td>
                <td>{{ $worker->getProfessionName->name }}</td>
                <td>
                    <a href="{{ route('workers.edit', $worker->id) }}">
                    Подробнее
                    </a>
                </td>
            </tr>
            @endforeach
            </tbody>
        </table>

    </div>

    <div class="d-flex justify-content-center">
        {{ $workers->links() }}
    </div>


@endsection