routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('home');
})->name('home');

/*Route::get('/workerAdd', 'WorkerController@view')->name('worker_add');
Route::get('/professions', 'ProfessionController@getList')->name('professions');
Route::get('/profession_add', function () {
    return view('professionAdd');
})->name('profession_add');*/

/*Route::get('/profession_edit/{id}', 'ProfessionController@view')->name('profession_edit');
Route::get('/profession_delete/{id}', 'ProfessionController@delete')->name('profession_delete');
Route::post('/profession_update_submit/{id}', 'ProfessionController@update')->name('profession_update_submit');
Route::post('/profession_submit', 'ProfessionController@update')->name('profession_submit');*/

/*Route::get('/workers', 'WorkerController@getList')->name('workers');
Route::get('/worker_update/{id}', 'WorkerController@view')->name('worker_update');
Route::get('/worker_delete/{id}', 'WorkerController@delete')->name('worker_delete');
Route::post('/worker_update_submit/{id}','WorkerController@update')->name('worker_update_submit');
Route::post('/worker_submit', 'WorkerController@update')->name('worker_submit');*/

/*Route::get('/city_add', 'RegionController@getList')->name('city_add');*/

/*Route::get('/cities', 'CityController@getList')->name('cities');
Route::get('/city_update/{id}', 'CityController@view')->name('city_update');
Route::get('/city_delete/{id}', 'CityController@delete')->name('city_delete');
Route::post('/city_update_submit/{id}', 'CityController@update')->name('city_update_submit');
Route::post('/city_submit', 'CityController@submit')->name('city_submit');*/

Route::resource('workers', 'WorkerController');
Route::resource('professions', 'ProfessionController');
Route::resource('cities', 'CityController',
    ['except' => ['show']]);
Route::resource('routes', 'RouteController',
    ['except' => ['create', 'show', 'edit' ]]);
Route::resource('routes', 'RouteController',
    ['except' => ['create', 'show', 'edit' ]]);
Route::resource('timetables', 'TimetableController',
    ['except' => ['show']]);
Route::post('check_busy_time', 'TimetableController@checkBusyTime')->name('check_busy_time');
Route::resource('buses', 'BusController',
    ['except' => ['create', 'show', 'edit' ]]);
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

resources/views/modal/busesModal.blade.php
<div class="modal fade modalWindow" id="newBusModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Новий запис</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form {{--method="POST" action="{{ route('buses.store') }}"--}} id="newBusForm">
                {{--{{ csrf_field() }}--}}

                <div class="modal-body">

                    <div>
                        <label for="model">Модель авто</label>
                        <input type="text" name="model" id="model" required>
                    </div>

                    <div>
                        <label for="carNumber">Номерний знак</label>
                        <input type="text" name="carNumber" id="carNumber" required>
                    </div>

                    <div>
                        <label for="seats">Кількість сидячих місць</label>
                        <input type="number" name="seats" id="seats" required>
                    </div>

                    <div>
                        <label for="fuelConsumption">Розхід топлива</label>
                        <input type="text" name="fuelConsumption" id="fuelConsumption" required>
                    </div>

                    <div>
                        <label for="typeOfTransportation">Тип маршруту</label>
                        <input type="text" name="typeOfTransportation" id="typeOfTransportation" required>
                    </div>

                    <div>
                        <label for="typeOfFuel">Тип палива</label>
                        <input type="text" name="typeOfFuel" id="typeOfFuel" required>
                    </div>

                    <div>
                        <label for="dateOfManufacture">Рік випуску авто</label>
                        <input type="number" name="dateOfManufacture" id="dateOfManufacture" required >
                    </div>

                    <div>
                        <label for="run">Пробіг авто</label>
                        <input type="number" name="run" id="run" required>
                    </div>

                    <div>
                        <label for="insuranceFrom">Дата страхування</label>
                        <input type="date" name="insuranceFrom" id="insuranceFrom" required >
                    </div>

                    <div>
                        <label for="insuranceTo">Дата закінчення страхування</label>
                        <input type="date" name="insuranceTo" id="insuranceTo" required>
                    </div>

                    <div id="result" style="color: #A52A2A" ></div>

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрити</button>
                    <button type="submit" id="saveNewBusBtn" class="btn btn-success" >Зберегти</button>
                </div>
            </form>
        </div>
    </div>
</div>

{{--EDIT TIMETABLE MODAL--}}
<div class="modal fade modalWindow" id="editBusModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editBusTitle"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="editBusForm" {{--method="POST" action="{{ route('buses.update', ['id' => $bus->id  ] ) }}"--}} role="modal" >
               {{-- {{ method_field('PATCH') }}
                {{ csrf_field() }}--}}

                <div class="modal-body">
                    <input type="hidden" name="id" id="idEdit" >

                <div>
                    <label for="model">Модель авто</label>
                    <input class="edit" type="text" name="model" id="model" required>
                </div>

                <div>
                    <label for="carNumber">Номерний знак</label>
                    <input class="edit" type="text" name="carNumber" id="carNumber" required>
                </div>

                <div>
                    <label for="seats">Кількість сидячих місць</label>
                    <input class="edit" type="number" name="seats" id="seats" required>
                </div>

                <div>
                    <label for="fuelConsumption">Розхід топлива</label>
                    <input class="edit" type="text" name="fuelConsumption" id="fuelConsumption" required>
                </div>

                <div>
                    <label for="typeOfTransportation">Тип маршруту</label>
                    <input class="edit" type="text" name="typeOfTransportation" id="typeOfTransportation" required>
                </div>

                <div>
                    <label for="typeOfFuel">Тип палива</label>
                    <input class="edit" type="text" name="typeOfFuel" id="typeOfFuel" required>
                </div>

                <div>
                    <label for="dateOfManufacture">Рік випуску авто</label>
                    <input class="edit" type="number" name="dateOfManufacture" id="dateOfManufacture" required >
                </div>

                <div>
                    <label for="run">Пробіг авто</label>
                    <input class="edit" type="number" name="run" id="run" required>
                </div>

                <div>
                    <label for="insuranceFrom">Дата страхування</label>
                    <input class="edit" type="date" name="insuranceFrom" id="insuranceFrom" required >
                </div>

                <div>
                    <label for="insuranceTo">Дата закінчення страхування</label>
                    <input class="edit" type="date" name="insuranceTo" id="insuranceTo" required>
                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрити</button>
                <button type="submit" id="updateBusBtn" class="btn btn-primary">Редагувати</button>
            </div>
            </form>

            {{-- DELETE CONTENT--}}
            <form id="deleteBusForm" {{--action="{{ route( 'buses.destroy', ['id' => $bus->id]) }}" method="POST" --}}>
                <div class="modal-body">
                    <input type="hidden" name="id" id="idDelete" >
                    <div class="deleteContentBus"> Дійсно бажаєте видалити запис?<span class="hidden id"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрити</button>
                    <button type="submit" id="deleteBusBtn" class="btn btn-danger">Видалити</button>
                </div>
            </form>

        </div>
    </div>
</div>

resources/views/modal/routeModal.blade.php
<div class="modal fade modalWindow" id="newRouteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Новий запис</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="newRouteForm">
            <div class="modal-body">
                    <div class="form-group">
                        <label  for="name">Назва маршруту</label>
                        <input class="route" type="text" name="name" id="name" placeholder="Назва" required>
                    </div>

                    <div class="form-group">
                        <label for="distance">Відстань</label>
                        <input class="route"  type="number" name="distance" id="distance"  placeholder="Відстань" required>
                    </div>

                    <div class="form-group">
                        <label  for="price">Ціна</label>
                        <input class="route" type="number" name="price" id="price"  placeholder="Ціна" required>
                    </div>
                <div id="result" style="color: #A52A2A" ></div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрити</button>
                <button type="submit" id="saveNewRouteBtn" class="btn btn-success">Зберегти</button>
            </div>

            </form>


        </div>
    </div>
</div>

{{--EDIT TIMETABLE MODAL--}}
<div class="modal fade modalWindow" id="editRouteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editRouteTitle"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="editRouteForm" role="modal">
            <div class="modal-body">
                    <input type="hidden" name="id" id="idEdit" >
                    <div class="form-group">
                        <label for="name">Назва маршруту</label>
                        <input class="edit" type="text" name="name" id="name" required>
                    </div>

                    <div class="form-group">
                        <label for="distance">Відстань</label>
                        <input class="edit" type="number" name="distance" id="distance" required>
                    </div>

                    <div class="form-group">
                        <label for="price">Ціна</label>
                        <input class="edit" type="number" name="price" id="price" required>
                    </div>
               {{-- <div id="result_edit" style="color: #A52A2A" ></div>--}}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрити</button>
                <button type="submit" id="updateRouteBtn" class="btn btn-primary">Редагувати</button>
            </div>
            </form>

            {{-- DELETE CONTENT--}}
            <form id="deleteRouteForm">
                <div class="modal-body">
                    <input type="hidden" name="id" id="idDelete" >
                    <div class="deleteContentRoute"> Дійсно бажаєте видалити запис?<span class="hidden id"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрити</button>
                    <button type="submit" id="deleteRouteBtn" class="btn btn-danger">Видалити</button>
                </div>

            </form>


        </div>
    </div>
</div>

resources/views/modal/timetablesModal.blade.php
@extends('layouts.app')
@section('content')
<div class="modal fade modalWindow" id="newTimetableModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Новий запис</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="newTimetableForm" >
                <div class="modal-body">
                    <div class="form-group">
                    <p>Маршрути :
                        <select class="field" id="route_id" name="route_id" required>
                            <option></option>
                            @foreach ($routes as $route)
                                <option value="{{ $route->id }}"> {{ $route->name }}</option>
                            @endforeach
                        </select>
                    </p>
                    </div>

                    <div class="form-group">
                    <p>Автобуси :
                        <select class="field" id="bus_id" name="bus_id" required>
                            <option></option>
                            @foreach ($buses as $bus)
                                <option value="{{ $bus->id }}"> {{ $bus->model . ' ' . $bus->carNumber }}</option>
                            @endforeach
                        </select>
                    </p>
                    </div>

                    <div class="form-group">
                    <p>Водії:
                        <select class="field" id="worker_id" name="worker_id" required>
                            <option></option>
                            @foreach ($drivers as $driver)
                                <option value="{{ $driver->id }}"> {{ $driver->firstName . ' ' . $driver->lastName }}</option>
                            @endforeach
                        </select>
                    </p>
                    </div>

                    <div class="form-group">
                        <label for="departureTime">Час відправлення</label>
                        <input class="field" type="datetime-local" name="departureTime"
                               id="departureTime" min="{{ date('Y-m-d\Th:i') }}"
                               required>
                    </div>
                    <div class="form-group">
                        <label for="arrivalTime">Час прибуття</label>
                        <input class="field" type="datetime-local" name="arrivalTime"
                               id="arrivalTime" min="{{ date('Y-m-d\Th:i') }}"
                               required>
                    </div>
                <div id="result" style="color: #A52A2A" ></div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрити</button>
                    <button type="submit" id="saveNewTimetableBtn" class="btn btn-success" >Зберегти</button>
                </div>
            </form>
        </div>
    </div>
</div>

                        {{--EDIT TIMETABLE MODAL--}}
<div class="modal fade modalWindow" id="editTimetableModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="editTimetableTitle"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form id="editTimetableForm" role="modal">
                <div class="modal-body">
                    <input type="hidden" name="id" id="idEdit" >
                    <div class="form-group">
                        <p>Маршрути :
                            <select class="edit" id="route_id" name="route_id" required>
                                @foreach ($routes as $route)
                                    <option value="{{ $route->id }}"> {{ $route->name }}</option>
                                @endforeach
                            </select>
                        </p>
                    </div>

                    <div class="form-group">
                        <p>Автобуси :
                            <select class="edit" id="bus_id" name="bus_id" required>
                                @foreach ($buses as $bus)
                                    <option value="{{ $bus->id }}"> {{ $bus->model . ' ' . $bus->carNumber }}</option>
                                @endforeach
                            </select>
                        </p>
                    </div>

                    <div class="form-group">
                        <p>Водії:
                            <select class="edit" id="worker_id" name="worker_id" required>
                                @foreach ($drivers as $driver)
                                    <option value="{{ $driver->id }}"> {{ $driver->firstName . ' ' . $driver->lastName }}</option>
                                @endforeach
                            </select>
                        </p>
                    </div>

                    <div class="form-group">
                        <label for="departureTime">Час відправлення</label>
                        <input class="edit" type="datetime-local" name="departureTime"
                               id="departureTime" min="{{ date('Y-m-d\Th:i') }}" required>
                    </div>
                    <div class="form-group">
                        <label for="arrivalTime">Час прибуття</label>
                        <input class="edit" type="datetime-local" name="arrivalTime"
                               id="arrivalTime" min="{{ date('Y-m-d\Th:i') }}" required>
                    </div>
                <div id="result_edit" style="color: #A52A2A" ></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрити</button>
                <button type="submit" id="updateTimetableBtn" class="btn btn-primary">Редагувати</button>
            </div>
            </form>
            {{-- DELETE CONTENT--}}
            <form id="deleteTimetableForm">
                <div class="modal-body">
                    <input type="hidden" name="id" id="idDelete" >
                    <div class="deleteContentTimetable"> Дійсно бажаєте видалити запис ?<span class="hidden id"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрити</button>
                    <button type="submit" id="deleteTimetableBtn" class="btn btn-danger">Видалити</button>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection