routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use Illuminate\Support\Facades\Route;

Route::get('/', function () {
    return view('home');
})->name('home');

/*Route::get('/workerAdd', 'WorkerController@view')->name('worker_add');
Route::get('/professions', 'ProfessionController@getList')->name('professions');
Route::get('/profession_add', function () {
    return view('professionAdd');
})->name('profession_add');*/

/*Route::get('/profession_edit/{id}', 'ProfessionController@view')->name('profession_edit');
Route::get('/profession_delete/{id}', 'ProfessionController@delete')->name('profession_delete');
Route::post('/profession_update_submit/{id}', 'ProfessionController@update')->name('profession_update_submit');
Route::post('/profession_submit', 'ProfessionController@update')->name('profession_submit');*/

/*Route::get('/workers', 'WorkerController@getList')->name('workers');
Route::get('/worker_update/{id}', 'WorkerController@view')->name('worker_update');
Route::get('/worker_delete/{id}', 'WorkerController@delete')->name('worker_delete');
Route::post('/worker_update_submit/{id}','WorkerController@update')->name('worker_update_submit');
Route::post('/worker_submit', 'WorkerController@update')->name('worker_submit');*/

/*Route::get('/city_add', 'RegionController@getList')->name('city_add');*/

/*Route::get('/cities', 'CityController@getList')->name('cities');
Route::get('/city_update/{id}', 'CityController@view')->name('city_update');
Route::get('/city_delete/{id}', 'CityController@delete')->name('city_delete');
Route::post('/city_update_submit/{id}', 'CityController@update')->name('city_update_submit');
Route::post('/city_submit', 'CityController@submit')->name('city_submit');*/

Route::resource('workers', 'WorkerController');
Route::resource('professions', 'ProfessionController');
Route::resource('cities', 'CityController',
    ['except' => ['show']]);
Route::resource('routes', 'RouteController',
    ['except' => ['create', 'show', 'edit' ]]);
Route::resource('routes', 'RouteController',
    ['except' => ['create', 'show', 'edit' ]]);
Route::resource('timetables', 'TimetableController',
    ['except' => ['show']]);
Route::post('check_busy_time', 'TimetableController@checkBusyTime')->name('check_busy_time');
Route::resource('buses', 'BusController',
    ['except' => ['create', 'show', 'edit' ]]);
Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

resources/views/includes/footer.blade.php
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<script src="{{ asset('js/app.js') }}"></script>
<script src="{{asset('js/dateFormat.js')}}"></script>
<script src="{{asset('js/timetable.js')}}"></script>
<script src="{{asset('js/route.js')}}"></script>
<script src="{{asset('js/bus.js')}}"></script>

resources/views/includes/header.blade.php
<div id="app">
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}"><b>AUTOPARK.UA</b></a>

            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <a class="navbar-brand" href="{{ route('home') }}">Головна</a>
                <a class="navbar-brand" href="{{ route('buses.index') }}">Автобуси</a>
                <a class="navbar-brand" href="{{ route('cities.index') }}">Населенные пункты</a>
                <a class="navbar-brand" href="{{ route('routes.index') }}">Маршрути</a>
                <a class="navbar-brand" href="{{ route('timetables.index') }}">Розклад руху</a>
                <a class="navbar-brand" href="{{ route('workers.index') }}">Персонал</a>
                <a class="navbar-brand" href="{{ route('professions.index') }}">Посади</a>
                <ul class="nav navbar-nav">
                    &nbsp;
                </ul>

                <!-- Right Side Of Navbar -->

                <ul class="nav navbar-nav navbar-right">

                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ route('login') }}">Вхід</a></li>
                        <li><a href="{{ route('register') }}">Зареєструватись</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->name }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>
                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>
</div>

resources/views/includes/messages.blade.php
@if($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif

@if(session('success'))
    <div class="alert alert-success">
        {{ session('success') }}
    </div>
@endif